### ISSUE TITLE
Wrong install location on CentOS 7

### ISSUE THREAD

**Issue by joeyboon** [nozel-org/serverbot#71]
CentOS uses a diffrent binary directory then the script uses. This causes some issues.

**Comment by sveeke** [comment]
Will be fixed in the next release. Thanks!

**Comment by sveeke** [comment]
`/usr/local/bin/serverbot` is being used in the current script, since that normally should be the recommended install location for scripts such as serverbot. But since not all linux distributions have this location added to their shell, `/usr/bin/serverbot` is probably better/more universal. I'll have to test this first.

Also `function serverbot_cron` has to be changed considerably when this gets changed.

**Comment by sveeke** [comment]
Fixed in https://github.com/nozel-org/serverbot/commit/672cabd650328137a10c76d41996242fd46c0a67. Needs testing.

**Comment by sveeke** [comment]
Tested on Fedora 31, CentOS 7 and Debian 8. Should work now :-).
